console.log("Hello World!");
document.body;
document.body.childNodes;
document.body.childNodes[1];
let cont = document.body.childNodes[1];
cont.childNodes[0];
cont.firstChild;
cont.firstElementChild;
cont.lastElementChild;
cont.lastElementChild.style.color = "red";
cont.lastElementChild.style.backgroundColor = "brown";
document.body.firstElementChild.childNodes;
document.body.firstElementChild.children;
document.body.firstElementChild.children[0];
document.body.firstElementChild.children[1];
document.body.firstElementChild.children[2];
document.body.firstElementChild.children[3];
document.body.firstElementChild.children[3].nextElementSibling;
document.body.firstElementChild.children[3].previousElementSibling;
document.body.firstElementChild.children[3].previousSibling;
document.body.firstElementChild.children[3].parentElement;